"""empty message

Revision ID: 905f0bf6ff91
Revises: f27b869e5f6b
Create Date: 2020-07-29 10:28:58.467265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905f0bf6ff91'
down_revision = 'f27b869e5f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('images', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'images')
    # ### end Alembic commands ###
